apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-Crud
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: demo-Crud
  template:
    metadata:
      labels:
        app: demo-Crud
    spec:
      containers:
      - name: demo-Crud-Container  

        image:  
        demo-Crud:Demo 
        ports:
        - containerPort: 8080